name       : gamehub
version    : 0.8.0
release    : 1
source     :
    - https://github.com/tkashkin/GameHub/archive/0.8.0.tar.gz : 259879f8c2bb9e22e93c717fdc0fcaaa098d8db7fe1437d57d29354dd2ef5de2
license    : WTFPL
component  : games.platformer
summary    : Games manager/downloader/library written in Vala
description: |
    Games manager/downloader/library written in Vala that supports GOG, Steam and Humble Bundle.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
