name       : gamehub
version    : 0.11.5.20
release    : 3
source     :
    - https://github.com/tkashkin/GameHub/archive/0.11.5-20-dev.tar.gz : dbe23b82fe68ec1a04e197f874174a9106618ea99b0c3d5cffcb7d6b6b757d95
license    : WTFPL
component  : games.platformer
summary    : Games manager/downloader/library written in Vala
description: |
    Games manager/downloader/library written in Vala that supports GOG, Steam and Humble Bundle.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
