name       : qomui
version    : 0.7.0
release    : 1
source     :
    -  https://github.com/corrad1nho/qomui/archive/v0.7.0.tar.gz : 8e46bc96630a16c875742bf0e8f2f720f754d7425e9a5a861b1d3e71bca84ae2
license    : GPL-3.0-or-later
component  : network.clients
summary    : OpenVPN Gui with advanced features and support for multiple providers
description: |
    Qomui (Qt OpenVPN Management UI) is an easy-to-use OpenVPN Gui for GNU/Linux with some unique features such as provider-independent support for double-hop connections. Qomui supports multiple providers with added convenience when using AirVPN, PIA, ProtonVPN, Windscribe or Mullvad.
builddeps  :
    - python-setuptools
rundeps  :
    - bind-utils
    - dnsmasq
    - libnotify
    - openvpn
    - python-beautifulsoup4
    - python-dbus
    - python-geoip
    - python-lxml
    - python-pexpect
    - python-psutil
    - python-qtpy
    - python-requests
    - python-simplejson
    - stunnel
build      : |
    %python3_setup
install    : |
    %python3_install
