name       : gbml
version    : 1.4.0.0
release    : 1
source     :
    - https://github.com/supremesonicbrazil/GBML/archive/v1.4.0.0.tar.gz : 681dd30a179f6644e1039a167cc79dcd0c21f5308adc373e5fd9e087fef29cbf
license    : GPL-3.0-or-later
component  : games.platformer
summary    : Gaming Backup Multitool for Linux
description: |
    Gaming Backup Multitool for Linux - Backup utility and database for Linux Steam games 
rundeps  :
    - steam
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Widgets)
    - sqlite3
build      : |
    ./BUILD.sh
install    : |
  install -Dm755 ./bin/gbml "$installdir"/usr/bin/gbml
  install -Dm644 ./bin/SteamLinuxGames.db "$installdir"/usr/share/gbml/SteamLinuxGames.db
  install -Dm644 ./bin/gaming-backup-multitool-linux.desktop "$installdir"/usr/share/applications/gaming-backup-multitool-linux.desktop
  cp -r ./img "$installdir"/usr/share/gbml
