name       : findfileconflicts
version    : 1.0.6
release    : 1
source     :
    - https://github.com/artemanufrij/findfileconflicts/archive/1.0.6.tar.gz : 454f29291808e2fd35904f9344a7fffce8611d8688bb22c85f9bc59ced1a23ec
license    : GPL-3.0-or-later
component  : system.utils
summary    : Helps to find file names which could have conflicts
description: |
   Helps to find file names which could have conflicts
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
