name       : geth
version    : 1.8.10
release    : 4
source     :
    -  https://github.com/ethereum/go-ethereum/archive/v1.8.3.tar.gz  : 6c935e33006ab26c69dc083c7b471759812cd8cef5e1ec783f005d3c58a98621
license    : LGPL-3.0
component  : desktop.library
summary    : Official golang implementation of the Ethereum protocol
description: |
    Official golang implementation of the Ethereum protocol
builddeps  :
    - golang
build      : |
    make all
install    : |
    install -Dm755 -t $installdir/usr/bin build/bin/*


