name       : screencast
version    : 0.1.9
release    : 2
source     :
    - https://github.com/artemanufrij/screencast/archive/0.1.9.tar.gz : 52b5a4824b5fe2ff9cddbbe34604c560780fa84a652e76d6eaff19a072c0d7b0
license    : GPL-3.0
component  : multimedia.video
summary    : Simple screen recorder
description: |
    Simple screen recorder, written especially for elementary OS.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(xtst)
setup      : |
build      : |
    %cmake
    %make
install    : |
    %make_install
