name       : ciano
version    : 0.1.9
release    : 2
source     :
    - https://github.com/robertsanseries/ciano/archive/0.1.9.tar.gz : 85de228b59c021bba33799c961fee780410a24626bee200b8daf3db723668cc3
license    : GPL-3.0
component  : multimedia.audio
summary    : Multimedia converter
description: |
    A simple multimedia file converter.
builddeps  :
    - pkgconfig(granite)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
