name       : imageburner
version    : 1.0.1
release    : 3
source     :
    - https://github.com/artemanufrij/imageburner/archive/1.0.1.tar.gz : 97143eb0330d8156bbb55153d33e7abead105b4647067347de01f32dbafddc5d
license    : GPL-3.0
component  : multimedia
summary    : A simple imageburner
description: |
    A simple imageburner.
builddeps  :
    - pkgconfig(granite)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
