name       : imageburner
version    : 0.1.15
release    : 2
source     :
    - https://github.com/artemanufrij/imageburner/archive/0.1.15.tar.gz : 23e1ef8876f828e9ea0f21305a93754ba6d9185abaa209b0b5fb4ebc7c121648
license    : GPL-3.0
component  : multimedia
summary    : A simple imageburner
description: |
    A simple imageburner.
builddeps  :
    - pkgconfig(granite)
    - cmake
    - vala
setup      : |
    %apply_patches
    mkdir cmake
    install -m 00644 $pkgfiles/cmake/*.cmake cmake/.
    %cmake .
build      : |
    %make
install    : |
    %make_install
