name       : palaura
version    : 1.0.1
release    : 1
source     :
    - https://github.com/lainsce/palaura/archive/1.0.1.tar.gz : 1d04a143c422d9a5f92a657178635580f65dc81b4d1d4ffabaf300d7a0fe3d0c
license    : GPL-3.0-or-later
component  : office
summary    : Find any word's definition with this handy dictionary
description: |
   Find any word's definition, and details about it, with this handy dictionary by your side.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
