name       : elementary-calendar
version    : 0.4.3
release    : 2
source     :
    - https://github.com/elementary/calendar/archive/4.2.3.tar.gz : 4f36334ec9402bb59998816fd1849be9e8eb6a3ee96df292efe79d322ee3aa09
license    : GPL-3.0-or-later
component  : office
summary    : Desktop calendar app designed for elementary OS
description: |
    Desktop calendar app designed for elementary OS
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(folks)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libedataserverui-1.2)
    - pkgconfig(libecal-1.2)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libical)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - cmake
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
