name       : elementary-calendar
version    : 0.4.2
release    : 1
source     :
    - https://github.com/elementary/calendar/archive/0.4.2.tar.gz : 089d95e2062d81ac5aaa72742248c34b8119288f4d1f9a25a9a0957462a54ff6
license    : GPL-3.0-or-later
component  : office
summary    : Desktop calendar app designed for elementary OS
description: |
    Desktop calendar app designed for elementary OS
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(champlain-gtk-0.12)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(folks)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libedataserverui-1.2)
    - pkgconfig(libecal-1.2)
    - pkgconfig(libical)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-2.4)
    - cmake
    - vala
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
