name       : coin
version    : 1.2.2
release    : 1
source     :
    - https://github.com/lainsce/coin/archive/1.2.2.tar.gz : 7b3896711424f335b2f84cdcbc67c487cb0c1e0f78d5f1696c02dd8e76a63172
license    : GPL-3.0-or-later
component  : office.finance
summary    : Never miss out on the monetary value of a virtual currency with this handy applet
description: |
   Track the virtual currencies in real world currency value with this handy applet

    Choose which currency and virtual currency to use for tracking
    Quit anytime with the shortcut Ctrl + Q
    Move the applet by dragging it from anywhere in the window
    Stays out of your way in the desktop
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
