name       : megasync
version    : 3.6.7.0
release    : 8
source     :
    - https://github.com/meganz/MEGAsync/archive/v3.6.7.0_Win.tar.gz : 7c896e97cc5de168ee75ce6b99f72e33c90dfe31da62ce00d9f4f5ae9f9a96ee
    - https://github.com/meganz/sdk/archive/v3.4.0.tar.gz :  0a13576ac3efb741dd67c43698a99ff1ff721cc806f28908cc0bdba808d4988b
license    : MEGA LIMITED CODE REVIEW LICENCE
component  : network.clients
summary    : Sync your files to your Mega account.
description: |
    Easy automated syncing between your computers and your MEGA Cloud Drive.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcares)
    - pkgconfig(libcurl)
    - pkgconfig(libmediainfo)
    - pkgconfig(libsodium)
    - pkgconfig(libuv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Svg)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
    - cryptopp-devel
setup      : |
    cd $workdir/src/MEGASync/mega
    tar -xf $sources/v3.4.0.tar.gz --strip 1 -C .
    %autogen --without-freeimage  \
     --without-termcap \
     --without-ffmpeg
    cd $workdir/src
    %configure
build      : |
    cd $workdir/src
    %qmake MEGA.pro
    lrelease MEGASync/MEGASync.pro
    %make
install    : |
    install -Dm 644 $workdir/LICENCE.md $installdir/usr/share/licenses/megasync/LICENCE.md
    install -Dm 644 $workdir/installer/terms.txt $installdir/usr/share/licenses/megasync/terms.txt
    install -Dm 755 $workdir/src/MEGASync/megasync $installdir/usr/bin/megasync
    install -Dm 644 $workdir/src/MEGASync/platform/linux/data/megasync.desktop $installdir/usr/share/applications/megasync.desktop
    for size in 16x16 32x32 48x48 128x128 256x256
    do
    install -Dm 644 $workdir/src/MEGASync/platform/linux/data/icons/hicolor/$size/apps/mega.png $installdir/usr/share/icons/hicolor/$size/apps/mega.png
    done
