name       : megasync
version    : 3.6.6.0
release    : 7
source     :
    - https://github.com/meganz/MEGAsync/archive/v3.6.6.0_Linux.tar.gz : 377a0b77b2506ebe0052d6366c3b5b74c3012cb4938e4df5e4b003677073f5fa
    - https://github.com/meganz/sdk/archive/v3.3.9.tar.gz :  522b63bf2f2d1eeff0644ef106fff94fcd4f6a844e01539cc6cfb30d16463dba
license    : MEGA LIMITED CODE REVIEW LICENCE
component  : network.clients
summary    : Sync your files to your Mega account.
description: |
    Easy automated syncing between your computers and your MEGA Cloud Drive.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcares)
    - pkgconfig(libcurl)
    - pkgconfig(libsodium)
    - pkgconfig(libuv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
    - cryptopp-devel
setup      : |
    cd $workdir/src/MEGASync/mega
    tar -xf $sources/v3.3.9.tar.gz --strip 1 -C .
    %autogen --without-freeimage  \
     --without-termcap \
     --without-ffmpeg
    cd $workdir/src
    %configure
build      : |
    cd $workdir/src
    %qmake MEGA.pro
    lrelease MEGASync/MEGASync.pro
    %make
install    : |
    install -Dm 644 $workdir/LICENCE.md $installdir/usr/share/licenses/megasync/LICENCE.md
    install -Dm 644 $workdir/installer/terms.txt $installdir/usr/share/licenses/megasync/terms.txt
    install -Dm 755 $workdir/src/MEGASync/megasync $installdir/usr/bin/megasync
    install -Dm 644 $workdir/src/MEGASync/platform/linux/data/megasync.desktop $installdir/usr/share/applications/megasync.desktop
    for size in 16x16 32x32 48x48 128x128 256x256
    do
    install -Dm 644 $workdir/src/MEGASync/platform/linux/data/icons/hicolor/$size/apps/mega.png $installdir/usr/share/icons/hicolor/$size/apps/mega.png
    done
