name       : multibootusb
version    : 9.2.0
release    : 1
source     :
    - https://github.com/mbusb/multibootusb/archive/v9.2.0.tar.gz : 1f1539e11e5ac8af2fc2379a22c2ad6b73759b2babbc165f7ff716240e922d7d
license    : GPL-2.0-or-later
component  : system.utils
summary    : Boot multiple live Linux distros from a usb flash drive.
description: |
    MultiBootUSB is a cross platform* software/utility to create multi boot live Linux on a removable USB disk. It is similar to UNetbootin but many distros can be installed, provided you have enough space on the disk. MultiBootUSB also provides an option to uninstall distro(s) at any time, if you wish.
rundeps  :
    - mtools
    - p7zip
    - parted
    - python3-dbus
    - python3-pyudev
    - python-qtpy
    - python-six
    - util-linux
setup      : |
    chmod 755 "$workdir/data/multibootusb.desktop"
install    : |
    %python3_install
